Repository TachyonicProject/luxon, pull requests merged in 2018-05, with the labels that each got.

#76 InfinityStone Code cleanup #13
  docs/source/wsgi/request.rst
  luxon/core/auth.py
  luxon/core/db/base/connection.py
  luxon/core/handlers/request.py
  luxon/core/handlers/wsgi/application.py
  luxon/core/policy/policy.py
  luxon/core/router.py
  luxon/core/session/sessioncookie.py
  luxon/ext/falcon/compiled.py
  luxon/structs/models/model.py
  luxon/structs/models/sqlmodel.py
  luxon/utils/imports.py
  luxon/utils/sql.py
Labels: 3 - Completed

#77 InfinityStone Code cleanup #13
  docs/source/wsgi/request.rst
  luxon/core/auth.py
  luxon/core/db/base/connection.py
  luxon/core/handlers/request.py
  luxon/core/handlers/wsgi/application.py
  luxon/core/policy/policy.py
  luxon/core/router.py
  luxon/core/session/sessioncookie.py
  luxon/ext/falcon/compiled.py
  luxon/structs/models/model.py
  luxon/structs/models/sqlmodel.py
  luxon/utils/imports.py
  luxon/utils/sql.py
Labels: 3 - Completed

#80 Photonic code cleanup #35
  luxon/core/app.py
  luxon/core/auth.py
  luxon/core/config/defaults.py
  luxon/core/utils/theme.py
  luxon/helpers/template.py
  luxon/utils/http.py
Labels: 2 - In Progress

#82 Current Luxon Documentation #11
  docs/source/cmd/index.rst
  docs/source/index.rst
  docs/source/minion/index.rst
  docs/source/tutorials/api.rst
  docs/source/tutorials/cmd.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/minion.rst
  docs/source/tutorials/wsgi_web.rst
  docs/source/utils/files.rst
  docs/source/utils/index.rst
  docs/source/utils/sql.rst
  docs/source/wsgi/index.rst
  luxon/utils/sql.py
Labels: 2 - In Progress, Docs

#83 Current Luxon Documentation #11
  docs/source/cmd/index.rst
  docs/source/index.rst
  docs/source/minion/index.rst
  docs/source/tutorials/api.rst
  docs/source/tutorials/cmd.rst
  docs/source/tutorials/index.rst
  docs/source/tutorials/minion.rst
  docs/source/tutorials/wsgi_web.rst
  docs/source/utils/files.rst
  docs/source/utils/index.rst
  docs/source/utils/sql.rst
  docs/source/wsgi/index.rst
  luxon/utils/sql.py
Labels: 2 - In Progress, Docs

#84 Photonic code cleanup #35
  luxon/core/handlers/request.py
  luxon/core/handlers/wsgi/application.py
  luxon/core/handlers/wsgi/request.py
  luxon/structs/container.py
Labels: 2 - In Progress, enhancement

#85 Photonic code cleanup #35
  luxon/core/handlers/request.py
  luxon/core/handlers/wsgi/application.py
  luxon/core/handlers/wsgi/request.py
  luxon/structs/container.py
Labels: 2 - In Progress, enhancement

#87 Photonic code cleanup #35
  luxon/core/handlers/wsgi/request.py
  luxon/utils/http.py
  luxon/utils/timezone.py
Labels: 2 - In Progress, enhancement
